# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: nlp.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'nlp.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tnlp.proto\x12\x15topicspace.corpus.nlp\"O\n\x0cTextDocument\x12\x0f\n\x07primary\x18\x01 \x01(\t\x12\x11\n\tsecondary\x18\x02 \x03(\t\x12\x0e\n\x06tokens\x18\x03 \x03(\t\x12\x0b\n\x03url\x18\x04 \x01(\t\"`\n\tTokenStat\x12\r\n\x05token\x18\x01 \x01(\t\x12\x0b\n\x03url\x18\x02 \x01(\t\x12\x11\n\tfrequency\x18\x03 \x01(\x04\x12\x15\n\rdoc_frequency\x18\x04 \x01(\x04\x12\r\n\x05index\x18\x05 \x01(\x04\"w\n\x0eSparseDocument\x12\x0b\n\x03url\x18\x01 \x01(\t\x12\x15\n\rprimary_index\x18\x02 \x01(\x04\x12\x17\n\x0fsecondary_index\x18\x03 \x03(\x04\x12\x13\n\x0btoken_index\x18\x04 \x03(\x04\x12\x13\n\x0btoken_tfidf\x18\x05 \x03(\x02\"D\n\x0f\x43ooccurrenceRow\x12\r\n\x05index\x18\x01 \x01(\x04\x12\x13\n\x0bother_index\x18\x02 \x03(\x04\x12\r\n\x05\x63ount\x18\x03 \x03(\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'nlp_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TEXTDOCUMENT']._serialized_start=36
  _globals['_TEXTDOCUMENT']._serialized_end=115
  _globals['_TOKENSTAT']._serialized_start=117
  _globals['_TOKENSTAT']._serialized_end=213
  _globals['_SPARSEDOCUMENT']._serialized_start=215
  _globals['_SPARSEDOCUMENT']._serialized_end=334
  _globals['_COOCCURRENCEROW']._serialized_start=336
  _globals['_COOCCURRENCEROW']._serialized_end=404
# @@protoc_insertion_point(module_scope)
